
// Generated by Cadence Genus(TM) Synthesis Solution GENUS15.20 - 15.20-p004_1
// Generated on: Feb 22 2025 23:16:27

// Verification Directory fv/csa_32 

module csa_32(clk, rst_n, a, b, c, s, cout);
  input clk, rst_n;
  input [31:0] a, b, c;
  output [32:0] s;
  output cout;
  wire clk, rst_n;
  wire [31:0] a, b, c;
  wire [32:0] s;
  wire cout;
  wire [31:0] c1_reg;
  wire [31:0] c2_reg;
  wire [31:0] s1_reg;
  wire cout_reg_912, n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  wire n_7, n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_27, n_28, n_29, n_30;
  wire n_31, n_32, n_33, n_34, n_35, n_36, n_37, n_38;
  wire n_39, n_40, n_41, n_42, n_43, n_44, n_45, n_46;
  wire n_47, n_48, n_49, n_50, n_51, n_52, n_53, n_54;
  wire n_55, n_56, n_57, n_58, n_59, n_60, n_61, n_62;
  wire n_63, n_64, n_65, n_66, n_67, n_68, n_69, n_70;
  wire n_71, n_72, n_73, n_74, n_75, n_76, n_77, n_78;
  wire n_79, n_80, n_81, n_82, n_83, n_84, n_85, n_86;
  wire n_87, n_88, n_89, n_90, n_91, n_92, n_93, n_94;
  wire n_95, n_96, n_97, n_98, n_99, n_100, n_101, n_102;
  wire n_103, n_104, n_105, n_106, n_107, n_108, n_109, n_110;
  wire n_111, n_112, n_113, n_114, n_115, n_116, n_117, n_118;
  wire n_119, n_120, n_121, n_122, n_123, n_124, n_125, n_126;
  wire n_127, \s_reg[0]_813 , \s_reg[1]_814 , \s_reg[2]_815 ,
       \s_reg[3]_816 , \s_reg[4]_817 , \s_reg[5]_818 , \s_reg[6]_819 ;
  wire \s_reg[7]_820 , \s_reg[8]_821 , \s_reg[9]_822 , \s_reg[10]_823 ,
       \s_reg[11]_824 , \s_reg[12]_825 , \s_reg[13]_826 ,
       \s_reg[14]_827 ;
  wire \s_reg[15]_828 , \s_reg[16]_829 , \s_reg[17]_830 ,
       \s_reg[18]_831 , \s_reg[19]_832 , \s_reg[20]_833 ,
       \s_reg[21]_834 , \s_reg[22]_835 ;
  wire \s_reg[23]_836 , \s_reg[24]_837 , \s_reg[25]_838 ,
       \s_reg[26]_839 , \s_reg[27]_840 , \s_reg[28]_841 ,
       \s_reg[29]_842 , \s_reg[30]_843 ;
  wire \s_reg[31]_844 , \s_reg[32]_845 ;
  sky130_fd_sc_hd__dfrtp_1 \s_reg[32] (.RESET_B (rst_n), .CLK (clk), .D
       (\s_reg[32]_845 ), .Q (s[32]));
  sky130_fd_sc_hd__dfrtp_1 cout_reg(.RESET_B (rst_n), .CLK (clk), .D
       (cout_reg_912), .Q (cout));
  sky130_fd_sc_hd__dfrtp_1 \s_reg_reg[32] (.RESET_B (rst_n), .CLK
       (clk), .D (n_127), .Q (\s_reg[32]_845 ));
  sky130_fd_sc_hd__dfrtp_1 cout_reg_reg(.RESET_B (rst_n), .CLK (clk),
       .D (n_126), .Q (cout_reg_912));
  sky130_fd_sc_hd__fa_1 g3246(.A (c1_reg[31]), .B (c2_reg[31]), .CIN
       (s1_reg[31]), .COUT (n_126), .SUM (n_127));
  sky130_fd_sc_hd__dfrtp_1 \s_reg[31] (.RESET_B (rst_n), .CLK (clk), .D
       (\s_reg[31]_844 ), .Q (s[31]));
  sky130_fd_sc_hd__dfrtp_1 \s_reg_reg[31] (.RESET_B (rst_n), .CLK
       (clk), .D (n_125), .Q (\s_reg[31]_844 ));
  sky130_fd_sc_hd__dfrtp_1 \c2_reg_reg[31] (.RESET_B (rst_n), .CLK
       (clk), .D (n_124), .Q (c2_reg[31]));
  sky130_fd_sc_hd__fa_1 g3250(.A (c1_reg[30]), .B (c2_reg[30]), .CIN
       (s1_reg[31]), .COUT (n_124), .SUM (n_125));
  sky130_fd_sc_hd__dfrtp_1 \s_reg[30] (.RESET_B (rst_n), .CLK (clk), .D
       (\s_reg[30]_843 ), .Q (s[30]));
  sky130_fd_sc_hd__dfrtp_1 \s_reg_reg[30] (.RESET_B (rst_n), .CLK
       (clk), .D (n_123), .Q (\s_reg[30]_843 ));
  sky130_fd_sc_hd__dfrtp_1 \c2_reg_reg[30] (.RESET_B (rst_n), .CLK
       (clk), .D (n_122), .Q (c2_reg[30]));
  sky130_fd_sc_hd__fa_1 g3254(.A (c1_reg[29]), .B (c2_reg[29]), .CIN
       (s1_reg[30]), .COUT (n_122), .SUM (n_123));
  sky130_fd_sc_hd__dfrtp_1 \s_reg[29] (.RESET_B (rst_n), .CLK (clk), .D
       (\s_reg[29]_842 ), .Q (s[29]));
  sky130_fd_sc_hd__dfrtp_1 \s_reg_reg[29] (.RESET_B (rst_n), .CLK
       (clk), .D (n_121), .Q (\s_reg[29]_842 ));
  sky130_fd_sc_hd__dfrtp_1 \c2_reg_reg[29] (.RESET_B (rst_n), .CLK
       (clk), .D (n_120), .Q (c2_reg[29]));
  sky130_fd_sc_hd__fa_1 g3258(.A (c1_reg[28]), .B (c2_reg[28]), .CIN
       (s1_reg[29]), .COUT (n_120), .SUM (n_121));
  sky130_fd_sc_hd__dfrtp_1 \s_reg[28] (.RESET_B (rst_n), .CLK (clk), .D
       (\s_reg[28]_841 ), .Q (s[28]));
  sky130_fd_sc_hd__dfrtp_1 \s_reg_reg[28] (.RESET_B (rst_n), .CLK
       (clk), .D (n_119), .Q (\s_reg[28]_841 ));
  sky130_fd_sc_hd__dfrtp_1 \c2_reg_reg[28] (.RESET_B (rst_n), .CLK
       (clk), .D (n_118), .Q (c2_reg[28]));
  sky130_fd_sc_hd__fa_1 g3262(.A (c1_reg[27]), .B (c2_reg[27]), .CIN
       (s1_reg[28]), .COUT (n_118), .SUM (n_119));
  sky130_fd_sc_hd__dfrtp_1 \s_reg[27] (.RESET_B (rst_n), .CLK (clk), .D
       (\s_reg[27]_840 ), .Q (s[27]));
  sky130_fd_sc_hd__dfrtp_1 \s_reg_reg[27] (.RESET_B (rst_n), .CLK
       (clk), .D (n_117), .Q (\s_reg[27]_840 ));
  sky130_fd_sc_hd__dfrtp_1 \c2_reg_reg[27] (.RESET_B (rst_n), .CLK
       (clk), .D (n_116), .Q (c2_reg[27]));
  sky130_fd_sc_hd__fa_1 g3266(.A (c1_reg[26]), .B (c2_reg[26]), .CIN
       (s1_reg[27]), .COUT (n_116), .SUM (n_117));
  sky130_fd_sc_hd__dfrtp_1 \s_reg[26] (.RESET_B (rst_n), .CLK (clk), .D
       (\s_reg[26]_839 ), .Q (s[26]));
  sky130_fd_sc_hd__dfrtp_1 \s_reg_reg[26] (.RESET_B (rst_n), .CLK
       (clk), .D (n_115), .Q (\s_reg[26]_839 ));
  sky130_fd_sc_hd__dfrtp_1 \c2_reg_reg[26] (.RESET_B (rst_n), .CLK
       (clk), .D (n_114), .Q (c2_reg[26]));
  sky130_fd_sc_hd__fa_1 g3270(.A (c1_reg[25]), .B (c2_reg[25]), .CIN
       (s1_reg[26]), .COUT (n_114), .SUM (n_115));
  sky130_fd_sc_hd__dfrtp_1 \s_reg[25] (.RESET_B (rst_n), .CLK (clk), .D
       (\s_reg[25]_838 ), .Q (s[25]));
  sky130_fd_sc_hd__dfrtp_1 \s_reg_reg[25] (.RESET_B (rst_n), .CLK
       (clk), .D (n_113), .Q (\s_reg[25]_838 ));
  sky130_fd_sc_hd__dfrtp_1 \c2_reg_reg[25] (.RESET_B (rst_n), .CLK
       (clk), .D (n_112), .Q (c2_reg[25]));
  sky130_fd_sc_hd__fa_1 g3274(.A (c1_reg[24]), .B (c2_reg[24]), .CIN
       (s1_reg[25]), .COUT (n_112), .SUM (n_113));
  sky130_fd_sc_hd__dfrtp_1 \s_reg[24] (.RESET_B (rst_n), .CLK (clk), .D
       (\s_reg[24]_837 ), .Q (s[24]));
  sky130_fd_sc_hd__dfrtp_1 \s_reg_reg[24] (.RESET_B (rst_n), .CLK
       (clk), .D (n_111), .Q (\s_reg[24]_837 ));
  sky130_fd_sc_hd__dfrtp_1 \c2_reg_reg[24] (.RESET_B (rst_n), .CLK
       (clk), .D (n_110), .Q (c2_reg[24]));
  sky130_fd_sc_hd__fa_1 g3278(.A (c1_reg[23]), .B (c2_reg[23]), .CIN
       (s1_reg[24]), .COUT (n_110), .SUM (n_111));
  sky130_fd_sc_hd__dfrtp_1 \s_reg[23] (.RESET_B (rst_n), .CLK (clk), .D
       (\s_reg[23]_836 ), .Q (s[23]));
  sky130_fd_sc_hd__dfrtp_1 \s_reg_reg[23] (.RESET_B (rst_n), .CLK
       (clk), .D (n_109), .Q (\s_reg[23]_836 ));
  sky130_fd_sc_hd__dfrtp_1 \c2_reg_reg[23] (.RESET_B (rst_n), .CLK
       (clk), .D (n_108), .Q (c2_reg[23]));
  sky130_fd_sc_hd__fa_1 g3282(.A (c1_reg[22]), .B (c2_reg[22]), .CIN
       (s1_reg[23]), .COUT (n_108), .SUM (n_109));
  sky130_fd_sc_hd__dfrtp_1 \s_reg[22] (.RESET_B (rst_n), .CLK (clk), .D
       (\s_reg[22]_835 ), .Q (s[22]));
  sky130_fd_sc_hd__dfrtp_1 \s_reg_reg[22] (.RESET_B (rst_n), .CLK
       (clk), .D (n_107), .Q (\s_reg[22]_835 ));
  sky130_fd_sc_hd__dfrtp_1 \c2_reg_reg[22] (.RESET_B (rst_n), .CLK
       (clk), .D (n_106), .Q (c2_reg[22]));
  sky130_fd_sc_hd__fa_1 g3286(.A (c1_reg[21]), .B (c2_reg[21]), .CIN
       (s1_reg[22]), .COUT (n_106), .SUM (n_107));
  sky130_fd_sc_hd__dfrtp_1 \s_reg[21] (.RESET_B (rst_n), .CLK (clk), .D
       (\s_reg[21]_834 ), .Q (s[21]));
  sky130_fd_sc_hd__dfrtp_1 \s_reg_reg[21] (.RESET_B (rst_n), .CLK
       (clk), .D (n_105), .Q (\s_reg[21]_834 ));
  sky130_fd_sc_hd__dfrtp_1 \c2_reg_reg[21] (.RESET_B (rst_n), .CLK
       (clk), .D (n_104), .Q (c2_reg[21]));
  sky130_fd_sc_hd__fa_1 g3290(.A (c1_reg[20]), .B (c2_reg[20]), .CIN
       (s1_reg[21]), .COUT (n_104), .SUM (n_105));
  sky130_fd_sc_hd__dfrtp_1 \s_reg[20] (.RESET_B (rst_n), .CLK (clk), .D
       (\s_reg[20]_833 ), .Q (s[20]));
  sky130_fd_sc_hd__dfrtp_1 \s_reg_reg[20] (.RESET_B (rst_n), .CLK
       (clk), .D (n_103), .Q (\s_reg[20]_833 ));
  sky130_fd_sc_hd__dfrtp_1 \c2_reg_reg[20] (.RESET_B (rst_n), .CLK
       (clk), .D (n_102), .Q (c2_reg[20]));
  sky130_fd_sc_hd__fa_1 g3294(.A (c1_reg[19]), .B (c2_reg[19]), .CIN
       (s1_reg[20]), .COUT (n_102), .SUM (n_103));
  sky130_fd_sc_hd__dfrtp_1 \s_reg[19] (.RESET_B (rst_n), .CLK (clk), .D
       (\s_reg[19]_832 ), .Q (s[19]));
  sky130_fd_sc_hd__dfrtp_1 \s_reg_reg[19] (.RESET_B (rst_n), .CLK
       (clk), .D (n_101), .Q (\s_reg[19]_832 ));
  sky130_fd_sc_hd__dfrtp_1 \c2_reg_reg[19] (.RESET_B (rst_n), .CLK
       (clk), .D (n_100), .Q (c2_reg[19]));
  sky130_fd_sc_hd__fa_1 g3298(.A (c1_reg[18]), .B (c2_reg[18]), .CIN
       (s1_reg[19]), .COUT (n_100), .SUM (n_101));
  sky130_fd_sc_hd__dfrtp_1 \s_reg[18] (.RESET_B (rst_n), .CLK (clk), .D
       (\s_reg[18]_831 ), .Q (s[18]));
  sky130_fd_sc_hd__dfrtp_1 \c2_reg_reg[18] (.RESET_B (rst_n), .CLK
       (clk), .D (n_98), .Q (c2_reg[18]));
  sky130_fd_sc_hd__dfrtp_1 \s_reg_reg[18] (.RESET_B (rst_n), .CLK
       (clk), .D (n_99), .Q (\s_reg[18]_831 ));
  sky130_fd_sc_hd__fa_1 g3302(.A (c1_reg[17]), .B (c2_reg[17]), .CIN
       (s1_reg[18]), .COUT (n_98), .SUM (n_99));
  sky130_fd_sc_hd__dfrtp_1 \s_reg[17] (.RESET_B (rst_n), .CLK (clk), .D
       (\s_reg[17]_830 ), .Q (s[17]));
  sky130_fd_sc_hd__dfrtp_1 \s_reg_reg[17] (.RESET_B (rst_n), .CLK
       (clk), .D (n_97), .Q (\s_reg[17]_830 ));
  sky130_fd_sc_hd__dfrtp_1 \c2_reg_reg[17] (.RESET_B (rst_n), .CLK
       (clk), .D (n_96), .Q (c2_reg[17]));
  sky130_fd_sc_hd__fa_1 g3306(.A (c1_reg[16]), .B (c2_reg[16]), .CIN
       (s1_reg[17]), .COUT (n_96), .SUM (n_97));
  sky130_fd_sc_hd__dfrtp_1 \s_reg[16] (.RESET_B (rst_n), .CLK (clk), .D
       (\s_reg[16]_829 ), .Q (s[16]));
  sky130_fd_sc_hd__dfrtp_1 \c2_reg_reg[16] (.RESET_B (rst_n), .CLK
       (clk), .D (n_94), .Q (c2_reg[16]));
  sky130_fd_sc_hd__dfrtp_1 \s_reg_reg[16] (.RESET_B (rst_n), .CLK
       (clk), .D (n_95), .Q (\s_reg[16]_829 ));
  sky130_fd_sc_hd__fa_1 g3310(.A (c1_reg[15]), .B (c2_reg[15]), .CIN
       (s1_reg[16]), .COUT (n_94), .SUM (n_95));
  sky130_fd_sc_hd__dfrtp_1 \s_reg[15] (.RESET_B (rst_n), .CLK (clk), .D
       (\s_reg[15]_828 ), .Q (s[15]));
  sky130_fd_sc_hd__dfrtp_1 \c2_reg_reg[15] (.RESET_B (rst_n), .CLK
       (clk), .D (n_92), .Q (c2_reg[15]));
  sky130_fd_sc_hd__dfrtp_1 \s_reg_reg[15] (.RESET_B (rst_n), .CLK
       (clk), .D (n_93), .Q (\s_reg[15]_828 ));
  sky130_fd_sc_hd__fa_1 g3314(.A (c1_reg[14]), .B (c2_reg[14]), .CIN
       (s1_reg[15]), .COUT (n_92), .SUM (n_93));
  sky130_fd_sc_hd__dfrtp_1 \s_reg[14] (.RESET_B (rst_n), .CLK (clk), .D
       (\s_reg[14]_827 ), .Q (s[14]));
  sky130_fd_sc_hd__dfrtp_1 \c2_reg_reg[14] (.RESET_B (rst_n), .CLK
       (clk), .D (n_90), .Q (c2_reg[14]));
  sky130_fd_sc_hd__dfrtp_1 \s_reg_reg[14] (.RESET_B (rst_n), .CLK
       (clk), .D (n_91), .Q (\s_reg[14]_827 ));
  sky130_fd_sc_hd__fa_1 g3318(.A (c1_reg[13]), .B (c2_reg[13]), .CIN
       (s1_reg[14]), .COUT (n_90), .SUM (n_91));
  sky130_fd_sc_hd__dfrtp_1 \s_reg[13] (.RESET_B (rst_n), .CLK (clk), .D
       (\s_reg[13]_826 ), .Q (s[13]));
  sky130_fd_sc_hd__dfrtp_1 \c2_reg_reg[13] (.RESET_B (rst_n), .CLK
       (clk), .D (n_88), .Q (c2_reg[13]));
  sky130_fd_sc_hd__dfrtp_1 \s_reg_reg[13] (.RESET_B (rst_n), .CLK
       (clk), .D (n_89), .Q (\s_reg[13]_826 ));
  sky130_fd_sc_hd__fa_1 g3322(.A (c1_reg[12]), .B (c2_reg[12]), .CIN
       (s1_reg[13]), .COUT (n_88), .SUM (n_89));
  sky130_fd_sc_hd__dfrtp_1 \s_reg[12] (.RESET_B (rst_n), .CLK (clk), .D
       (\s_reg[12]_825 ), .Q (s[12]));
  sky130_fd_sc_hd__dfrtp_1 \c2_reg_reg[12] (.RESET_B (rst_n), .CLK
       (clk), .D (n_86), .Q (c2_reg[12]));
  sky130_fd_sc_hd__dfrtp_1 \s_reg_reg[12] (.RESET_B (rst_n), .CLK
       (clk), .D (n_87), .Q (\s_reg[12]_825 ));
  sky130_fd_sc_hd__fa_1 g3326(.A (c1_reg[11]), .B (c2_reg[11]), .CIN
       (s1_reg[12]), .COUT (n_86), .SUM (n_87));
  sky130_fd_sc_hd__dfrtp_1 \s_reg[11] (.RESET_B (rst_n), .CLK (clk), .D
       (\s_reg[11]_824 ), .Q (s[11]));
  sky130_fd_sc_hd__dfrtp_1 \c2_reg_reg[11] (.RESET_B (rst_n), .CLK
       (clk), .D (n_84), .Q (c2_reg[11]));
  sky130_fd_sc_hd__dfrtp_1 \s_reg_reg[11] (.RESET_B (rst_n), .CLK
       (clk), .D (n_85), .Q (\s_reg[11]_824 ));
  sky130_fd_sc_hd__fa_1 g3330(.A (c1_reg[10]), .B (c2_reg[10]), .CIN
       (s1_reg[11]), .COUT (n_84), .SUM (n_85));
  sky130_fd_sc_hd__dfrtp_1 \s_reg[10] (.RESET_B (rst_n), .CLK (clk), .D
       (\s_reg[10]_823 ), .Q (s[10]));
  sky130_fd_sc_hd__dfrtp_1 \c2_reg_reg[10] (.RESET_B (rst_n), .CLK
       (clk), .D (n_82), .Q (c2_reg[10]));
  sky130_fd_sc_hd__dfrtp_1 \s_reg_reg[10] (.RESET_B (rst_n), .CLK
       (clk), .D (n_83), .Q (\s_reg[10]_823 ));
  sky130_fd_sc_hd__fa_1 g3334(.A (c1_reg[9]), .B (c2_reg[9]), .CIN
       (s1_reg[10]), .COUT (n_82), .SUM (n_83));
  sky130_fd_sc_hd__dfrtp_1 \s_reg[9] (.RESET_B (rst_n), .CLK (clk), .D
       (\s_reg[9]_822 ), .Q (s[9]));
  sky130_fd_sc_hd__dfrtp_1 \c2_reg_reg[9] (.RESET_B (rst_n), .CLK
       (clk), .D (n_80), .Q (c2_reg[9]));
  sky130_fd_sc_hd__dfrtp_1 \s_reg_reg[9] (.RESET_B (rst_n), .CLK (clk),
       .D (n_81), .Q (\s_reg[9]_822 ));
  sky130_fd_sc_hd__fa_1 g3338(.A (c1_reg[8]), .B (c2_reg[8]), .CIN
       (s1_reg[9]), .COUT (n_80), .SUM (n_81));
  sky130_fd_sc_hd__dfrtp_1 \s_reg[8] (.RESET_B (rst_n), .CLK (clk), .D
       (\s_reg[8]_821 ), .Q (s[8]));
  sky130_fd_sc_hd__dfrtp_1 \s_reg_reg[8] (.RESET_B (rst_n), .CLK (clk),
       .D (n_79), .Q (\s_reg[8]_821 ));
  sky130_fd_sc_hd__dfrtp_1 \c2_reg_reg[8] (.RESET_B (rst_n), .CLK
       (clk), .D (n_78), .Q (c2_reg[8]));
  sky130_fd_sc_hd__fa_1 g3342(.A (c1_reg[7]), .B (c2_reg[7]), .CIN
       (s1_reg[8]), .COUT (n_78), .SUM (n_79));
  sky130_fd_sc_hd__dfrtp_1 \s_reg[7] (.RESET_B (rst_n), .CLK (clk), .D
       (\s_reg[7]_820 ), .Q (s[7]));
  sky130_fd_sc_hd__dfrtp_1 \s_reg_reg[7] (.RESET_B (rst_n), .CLK (clk),
       .D (n_77), .Q (\s_reg[7]_820 ));
  sky130_fd_sc_hd__dfrtp_1 \c2_reg_reg[7] (.RESET_B (rst_n), .CLK
       (clk), .D (n_76), .Q (c2_reg[7]));
  sky130_fd_sc_hd__fa_1 g3346(.A (c1_reg[6]), .B (c2_reg[6]), .CIN
       (s1_reg[7]), .COUT (n_76), .SUM (n_77));
  sky130_fd_sc_hd__dfrtp_1 \s_reg[6] (.RESET_B (rst_n), .CLK (clk), .D
       (\s_reg[6]_819 ), .Q (s[6]));
  sky130_fd_sc_hd__dfrtp_1 \s_reg_reg[6] (.RESET_B (rst_n), .CLK (clk),
       .D (n_75), .Q (\s_reg[6]_819 ));
  sky130_fd_sc_hd__dfrtp_1 \c2_reg_reg[6] (.RESET_B (rst_n), .CLK
       (clk), .D (n_74), .Q (c2_reg[6]));
  sky130_fd_sc_hd__fa_1 g3350(.A (c1_reg[5]), .B (c2_reg[5]), .CIN
       (s1_reg[6]), .COUT (n_74), .SUM (n_75));
  sky130_fd_sc_hd__dfrtp_1 \s_reg[5] (.RESET_B (rst_n), .CLK (clk), .D
       (\s_reg[5]_818 ), .Q (s[5]));
  sky130_fd_sc_hd__dfrtp_1 \s_reg_reg[5] (.RESET_B (rst_n), .CLK (clk),
       .D (n_73), .Q (\s_reg[5]_818 ));
  sky130_fd_sc_hd__dfrtp_1 \c2_reg_reg[5] (.RESET_B (rst_n), .CLK
       (clk), .D (n_72), .Q (c2_reg[5]));
  sky130_fd_sc_hd__fa_1 g3354(.A (c1_reg[4]), .B (c2_reg[4]), .CIN
       (s1_reg[5]), .COUT (n_72), .SUM (n_73));
  sky130_fd_sc_hd__dfrtp_1 \s_reg[4] (.RESET_B (rst_n), .CLK (clk), .D
       (\s_reg[4]_817 ), .Q (s[4]));
  sky130_fd_sc_hd__dfrtp_1 \s_reg_reg[4] (.RESET_B (rst_n), .CLK (clk),
       .D (n_71), .Q (\s_reg[4]_817 ));
  sky130_fd_sc_hd__dfrtp_1 \c2_reg_reg[4] (.RESET_B (rst_n), .CLK
       (clk), .D (n_70), .Q (c2_reg[4]));
  sky130_fd_sc_hd__fa_1 g3358(.A (c1_reg[3]), .B (c2_reg[3]), .CIN
       (s1_reg[4]), .COUT (n_70), .SUM (n_71));
  sky130_fd_sc_hd__dfrtp_1 \s_reg[3] (.RESET_B (rst_n), .CLK (clk), .D
       (\s_reg[3]_816 ), .Q (s[3]));
  sky130_fd_sc_hd__dfrtp_1 \c2_reg_reg[3] (.RESET_B (rst_n), .CLK
       (clk), .D (n_68), .Q (c2_reg[3]));
  sky130_fd_sc_hd__dfrtp_1 \s_reg_reg[3] (.RESET_B (rst_n), .CLK (clk),
       .D (n_69), .Q (\s_reg[3]_816 ));
  sky130_fd_sc_hd__fa_1 g3362(.A (c1_reg[2]), .B (c2_reg[2]), .CIN
       (s1_reg[3]), .COUT (n_68), .SUM (n_69));
  sky130_fd_sc_hd__dfrtp_1 \s_reg[2] (.RESET_B (rst_n), .CLK (clk), .D
       (\s_reg[2]_815 ), .Q (s[2]));
  sky130_fd_sc_hd__dfrtp_1 \s_reg_reg[2] (.RESET_B (rst_n), .CLK (clk),
       .D (n_67), .Q (\s_reg[2]_815 ));
  sky130_fd_sc_hd__dfrtp_1 \c2_reg_reg[2] (.RESET_B (rst_n), .CLK
       (clk), .D (n_66), .Q (c2_reg[2]));
  sky130_fd_sc_hd__fa_1 g3366(.A (c1_reg[1]), .B (c2_reg[1]), .CIN
       (s1_reg[2]), .COUT (n_66), .SUM (n_67));
  sky130_fd_sc_hd__dfrtp_1 \s_reg[1] (.RESET_B (rst_n), .CLK (clk), .D
       (\s_reg[1]_814 ), .Q (s[1]));
  sky130_fd_sc_hd__dfrtp_1 \s_reg_reg[1] (.RESET_B (rst_n), .CLK (clk),
       .D (n_65), .Q (\s_reg[1]_814 ));
  sky130_fd_sc_hd__dfrtp_1 \c2_reg_reg[1] (.RESET_B (rst_n), .CLK
       (clk), .D (n_64), .Q (c2_reg[1]));
  sky130_fd_sc_hd__ha_1 g3370(.A (s1_reg[1]), .B (c1_reg[0]), .COUT
       (n_64), .SUM (n_65));
  sky130_fd_sc_hd__dfrtp_1 \s_reg[0] (.RESET_B (rst_n), .CLK (clk), .D
       (\s_reg[0]_813 ), .Q (s[0]));
  sky130_fd_sc_hd__dfrtp_1 \s_reg_reg[0] (.RESET_B (rst_n), .CLK (clk),
       .D (s1_reg[0]), .Q (\s_reg[0]_813 ));
  sky130_fd_sc_hd__dfrtp_1 \c1_reg_reg[11] (.RESET_B (rst_n), .CLK
       (clk), .D (n_16), .Q (c1_reg[11]));
  sky130_fd_sc_hd__dfrtp_1 \s1_reg_reg[18] (.RESET_B (rst_n), .CLK
       (clk), .D (n_53), .Q (s1_reg[18]));
  sky130_fd_sc_hd__dfrtp_1 \s1_reg_reg[29] (.RESET_B (rst_n), .CLK
       (clk), .D (n_47), .Q (s1_reg[29]));
  sky130_fd_sc_hd__dfrtp_1 \s1_reg_reg[17] (.RESET_B (rst_n), .CLK
       (clk), .D (n_45), .Q (s1_reg[17]));
  sky130_fd_sc_hd__dfrtp_1 \c1_reg_reg[0] (.RESET_B (rst_n), .CLK
       (clk), .D (n_10), .Q (c1_reg[0]));
  sky130_fd_sc_hd__dfrtp_1 \s1_reg_reg[16] (.RESET_B (rst_n), .CLK
       (clk), .D (n_27), .Q (s1_reg[16]));
  sky130_fd_sc_hd__dfrtp_1 \s1_reg_reg[21] (.RESET_B (rst_n), .CLK
       (clk), .D (n_15), .Q (s1_reg[21]));
  sky130_fd_sc_hd__dfrtp_1 \s1_reg_reg[15] (.RESET_B (rst_n), .CLK
       (clk), .D (n_25), .Q (s1_reg[15]));
  sky130_fd_sc_hd__dfrtp_1 \s1_reg_reg[14] (.RESET_B (rst_n), .CLK
       (clk), .D (n_23), .Q (s1_reg[14]));
  sky130_fd_sc_hd__dfrtp_1 \s1_reg_reg[13] (.RESET_B (rst_n), .CLK
       (clk), .D (n_5), .Q (s1_reg[13]));
  sky130_fd_sc_hd__dfrtp_1 \s1_reg_reg[12] (.RESET_B (rst_n), .CLK
       (clk), .D (n_19), .Q (s1_reg[12]));
  sky130_fd_sc_hd__dfrtp_1 \s1_reg_reg[10] (.RESET_B (rst_n), .CLK
       (clk), .D (n_13), .Q (s1_reg[10]));
  sky130_fd_sc_hd__dfrtp_1 \s1_reg_reg[11] (.RESET_B (rst_n), .CLK
       (clk), .D (n_17), .Q (s1_reg[11]));
  sky130_fd_sc_hd__dfrtp_1 \c1_reg_reg[10] (.RESET_B (rst_n), .CLK
       (clk), .D (n_12), .Q (c1_reg[10]));
  sky130_fd_sc_hd__dfrtp_1 \c1_reg_reg[13] (.RESET_B (rst_n), .CLK
       (clk), .D (n_4), .Q (c1_reg[13]));
  sky130_fd_sc_hd__dfrtp_1 \c1_reg_reg[31] (.RESET_B (rst_n), .CLK
       (clk), .D (n_62), .Q (c1_reg[31]));
  sky130_fd_sc_hd__dfrtp_1 \s1_reg_reg[20] (.RESET_B (rst_n), .CLK
       (clk), .D (n_55), .Q (s1_reg[20]));
  sky130_fd_sc_hd__dfrtp_1 \c1_reg_reg[14] (.RESET_B (rst_n), .CLK
       (clk), .D (n_22), .Q (c1_reg[14]));
  sky130_fd_sc_hd__dfrtp_1 \c1_reg_reg[9] (.RESET_B (rst_n), .CLK
       (clk), .D (n_34), .Q (c1_reg[9]));
  sky130_fd_sc_hd__dfrtp_1 \c1_reg_reg[8] (.RESET_B (rst_n), .CLK
       (clk), .D (n_2), .Q (c1_reg[8]));
  sky130_fd_sc_hd__dfrtp_1 \c1_reg_reg[7] (.RESET_B (rst_n), .CLK
       (clk), .D (n_56), .Q (c1_reg[7]));
  sky130_fd_sc_hd__dfrtp_1 \c1_reg_reg[1] (.RESET_B (rst_n), .CLK
       (clk), .D (n_60), .Q (c1_reg[1]));
  sky130_fd_sc_hd__dfrtp_1 \c1_reg_reg[12] (.RESET_B (rst_n), .CLK
       (clk), .D (n_18), .Q (c1_reg[12]));
  sky130_fd_sc_hd__dfrtp_1 \c1_reg_reg[24] (.RESET_B (rst_n), .CLK
       (clk), .D (n_0), .Q (c1_reg[24]));
  sky130_fd_sc_hd__dfrtp_1 \c1_reg_reg[15] (.RESET_B (rst_n), .CLK
       (clk), .D (n_24), .Q (c1_reg[15]));
  sky130_fd_sc_hd__dfrtp_1 \c1_reg_reg[17] (.RESET_B (rst_n), .CLK
       (clk), .D (n_44), .Q (c1_reg[17]));
  sky130_fd_sc_hd__dfrtp_1 \c1_reg_reg[6] (.RESET_B (rst_n), .CLK
       (clk), .D (n_28), .Q (c1_reg[6]));
  sky130_fd_sc_hd__dfrtp_1 \c1_reg_reg[16] (.RESET_B (rst_n), .CLK
       (clk), .D (n_26), .Q (c1_reg[16]));
  sky130_fd_sc_hd__dfrtp_1 \c1_reg_reg[5] (.RESET_B (rst_n), .CLK
       (clk), .D (n_40), .Q (c1_reg[5]));
  sky130_fd_sc_hd__dfrtp_1 \c1_reg_reg[4] (.RESET_B (rst_n), .CLK
       (clk), .D (n_48), .Q (c1_reg[4]));
  sky130_fd_sc_hd__dfrtp_1 \c1_reg_reg[3] (.RESET_B (rst_n), .CLK
       (clk), .D (n_32), .Q (c1_reg[3]));
  sky130_fd_sc_hd__dfrtp_1 \s1_reg_reg[31] (.RESET_B (rst_n), .CLK
       (clk), .D (n_63), .Q (s1_reg[31]));
  sky130_fd_sc_hd__dfrtp_1 \s1_reg_reg[1] (.RESET_B (rst_n), .CLK
       (clk), .D (n_61), .Q (s1_reg[1]));
  sky130_fd_sc_hd__dfrtp_1 \s1_reg_reg[19] (.RESET_B (rst_n), .CLK
       (clk), .D (n_39), .Q (s1_reg[19]));
  sky130_fd_sc_hd__dfrtp_1 \s1_reg_reg[30] (.RESET_B (rst_n), .CLK
       (clk), .D (n_59), .Q (s1_reg[30]));
  sky130_fd_sc_hd__dfrtp_1 \s1_reg_reg[22] (.RESET_B (rst_n), .CLK
       (clk), .D (n_43), .Q (s1_reg[22]));
  sky130_fd_sc_hd__dfrtp_1 \s1_reg_reg[9] (.RESET_B (rst_n), .CLK
       (clk), .D (n_35), .Q (s1_reg[9]));
  sky130_fd_sc_hd__dfrtp_1 \s1_reg_reg[8] (.RESET_B (rst_n), .CLK
       (clk), .D (n_3), .Q (s1_reg[8]));
  sky130_fd_sc_hd__dfrtp_1 \s1_reg_reg[23] (.RESET_B (rst_n), .CLK
       (clk), .D (n_51), .Q (s1_reg[23]));
  sky130_fd_sc_hd__dfrtp_1 \s1_reg_reg[24] (.RESET_B (rst_n), .CLK
       (clk), .D (n_1), .Q (s1_reg[24]));
  sky130_fd_sc_hd__dfrtp_1 \s1_reg_reg[28] (.RESET_B (rst_n), .CLK
       (clk), .D (n_9), .Q (s1_reg[28]));
  sky130_fd_sc_hd__dfrtp_1 \s1_reg_reg[25] (.RESET_B (rst_n), .CLK
       (clk), .D (n_31), .Q (s1_reg[25]));
  sky130_fd_sc_hd__dfrtp_1 \s1_reg_reg[7] (.RESET_B (rst_n), .CLK
       (clk), .D (n_57), .Q (s1_reg[7]));
  sky130_fd_sc_hd__dfrtp_1 \s1_reg_reg[26] (.RESET_B (rst_n), .CLK
       (clk), .D (n_21), .Q (s1_reg[26]));
  sky130_fd_sc_hd__dfrtp_1 \s1_reg_reg[6] (.RESET_B (rst_n), .CLK
       (clk), .D (n_29), .Q (s1_reg[6]));
  sky130_fd_sc_hd__dfrtp_1 \s1_reg_reg[27] (.RESET_B (rst_n), .CLK
       (clk), .D (n_7), .Q (s1_reg[27]));
  sky130_fd_sc_hd__dfrtp_1 \s1_reg_reg[5] (.RESET_B (rst_n), .CLK
       (clk), .D (n_41), .Q (s1_reg[5]));
  sky130_fd_sc_hd__dfrtp_1 \s1_reg_reg[4] (.RESET_B (rst_n), .CLK
       (clk), .D (n_49), .Q (s1_reg[4]));
  sky130_fd_sc_hd__dfrtp_1 \s1_reg_reg[0] (.RESET_B (rst_n), .CLK
       (clk), .D (n_11), .Q (s1_reg[0]));
  sky130_fd_sc_hd__dfrtp_1 \s1_reg_reg[3] (.RESET_B (rst_n), .CLK
       (clk), .D (n_33), .Q (s1_reg[3]));
  sky130_fd_sc_hd__dfrtp_1 \s1_reg_reg[2] (.RESET_B (rst_n), .CLK
       (clk), .D (n_37), .Q (s1_reg[2]));
  sky130_fd_sc_hd__dfrtp_1 \c1_reg_reg[23] (.RESET_B (rst_n), .CLK
       (clk), .D (n_50), .Q (c1_reg[23]));
  sky130_fd_sc_hd__dfrtp_1 \c1_reg_reg[25] (.RESET_B (rst_n), .CLK
       (clk), .D (n_30), .Q (c1_reg[25]));
  sky130_fd_sc_hd__dfrtp_1 \c1_reg_reg[26] (.RESET_B (rst_n), .CLK
       (clk), .D (n_20), .Q (c1_reg[26]));
  sky130_fd_sc_hd__dfrtp_1 \c1_reg_reg[21] (.RESET_B (rst_n), .CLK
       (clk), .D (n_14), .Q (c1_reg[21]));
  sky130_fd_sc_hd__dfrtp_1 \c1_reg_reg[27] (.RESET_B (rst_n), .CLK
       (clk), .D (n_6), .Q (c1_reg[27]));
  sky130_fd_sc_hd__dfrtp_1 \c1_reg_reg[20] (.RESET_B (rst_n), .CLK
       (clk), .D (n_54), .Q (c1_reg[20]));
  sky130_fd_sc_hd__dfrtp_1 \c1_reg_reg[28] (.RESET_B (rst_n), .CLK
       (clk), .D (n_8), .Q (c1_reg[28]));
  sky130_fd_sc_hd__dfrtp_1 \c1_reg_reg[19] (.RESET_B (rst_n), .CLK
       (clk), .D (n_38), .Q (c1_reg[19]));
  sky130_fd_sc_hd__dfrtp_1 \c1_reg_reg[29] (.RESET_B (rst_n), .CLK
       (clk), .D (n_46), .Q (c1_reg[29]));
  sky130_fd_sc_hd__dfrtp_1 \c1_reg_reg[22] (.RESET_B (rst_n), .CLK
       (clk), .D (n_42), .Q (c1_reg[22]));
  sky130_fd_sc_hd__dfrtp_1 \c1_reg_reg[2] (.RESET_B (rst_n), .CLK
       (clk), .D (n_36), .Q (c1_reg[2]));
  sky130_fd_sc_hd__dfrtp_1 \c1_reg_reg[30] (.RESET_B (rst_n), .CLK
       (clk), .D (n_58), .Q (c1_reg[30]));
  sky130_fd_sc_hd__dfrtp_1 \c1_reg_reg[18] (.RESET_B (rst_n), .CLK
       (clk), .D (n_52), .Q (c1_reg[18]));
  sky130_fd_sc_hd__fa_1 g3437(.A (a[31]), .B (c[31]), .CIN (b[31]),
       .COUT (n_62), .SUM (n_63));
  sky130_fd_sc_hd__fa_1 g3468(.A (a[1]), .B (c[1]), .CIN (b[1]), .COUT
       (n_60), .SUM (n_61));
  sky130_fd_sc_hd__fa_1 g3442(.A (a[30]), .B (c[30]), .CIN (b[30]),
       .COUT (n_58), .SUM (n_59));
  sky130_fd_sc_hd__fa_1 g3457(.A (a[7]), .B (c[7]), .CIN (b[7]), .COUT
       (n_56), .SUM (n_57));
  sky130_fd_sc_hd__fa_1 g3456(.A (a[20]), .B (c[20]), .CIN (b[20]),
       .COUT (n_54), .SUM (n_55));
  sky130_fd_sc_hd__fa_1 g3464(.A (a[18]), .B (c[18]), .CIN (b[18]),
       .COUT (n_52), .SUM (n_53));
  sky130_fd_sc_hd__fa_1 g3446(.A (a[23]), .B (c[23]), .CIN (b[23]),
       .COUT (n_50), .SUM (n_51));
  sky130_fd_sc_hd__fa_1 g3463(.A (a[4]), .B (c[4]), .CIN (b[4]), .COUT
       (n_48), .SUM (n_49));
  sky130_fd_sc_hd__fa_1 g3458(.A (a[29]), .B (c[29]), .CIN (b[29]),
       .COUT (n_46), .SUM (n_47));
  sky130_fd_sc_hd__fa_1 g3467(.A (a[17]), .B (c[17]), .CIN (b[17]),
       .COUT (n_44), .SUM (n_45));
  sky130_fd_sc_hd__fa_1 g3450(.A (a[22]), .B (c[22]), .CIN (b[22]),
       .COUT (n_42), .SUM (n_43));
  sky130_fd_sc_hd__fa_1 g3461(.A (a[5]), .B (c[5]), .CIN (b[5]), .COUT
       (n_40), .SUM (n_41));
  sky130_fd_sc_hd__fa_1 g3460(.A (a[19]), .B (c[19]), .CIN (b[19]),
       .COUT (n_38), .SUM (n_39));
  sky130_fd_sc_hd__fa_1 g3466(.A (a[2]), .B (c[2]), .CIN (b[2]), .COUT
       (n_36), .SUM (n_37));
  sky130_fd_sc_hd__fa_1 g3454(.A (a[9]), .B (c[9]), .CIN (b[9]), .COUT
       (n_34), .SUM (n_35));
  sky130_fd_sc_hd__fa_1 g3465(.A (a[3]), .B (c[3]), .CIN (b[3]), .COUT
       (n_32), .SUM (n_33));
  sky130_fd_sc_hd__fa_1 g3462(.A (a[25]), .B (c[25]), .CIN (b[25]),
       .COUT (n_30), .SUM (n_31));
  sky130_fd_sc_hd__fa_1 g3459(.A (a[6]), .B (c[6]), .CIN (b[6]), .COUT
       (n_28), .SUM (n_29));
  sky130_fd_sc_hd__fa_1 g3441(.A (a[16]), .B (c[16]), .CIN (b[16]),
       .COUT (n_26), .SUM (n_27));
  sky130_fd_sc_hd__fa_1 g3443(.A (a[15]), .B (c[15]), .CIN (b[15]),
       .COUT (n_24), .SUM (n_25));
  sky130_fd_sc_hd__fa_1 g3445(.A (a[14]), .B (c[14]), .CIN (b[14]),
       .COUT (n_22), .SUM (n_23));
  sky130_fd_sc_hd__fa_1 g3455(.A (a[26]), .B (c[26]), .CIN (b[26]),
       .COUT (n_20), .SUM (n_21));
  sky130_fd_sc_hd__fa_1 g3449(.A (a[12]), .B (c[12]), .CIN (b[12]),
       .COUT (n_18), .SUM (n_19));
  sky130_fd_sc_hd__fa_1 g3451(.A (a[11]), .B (c[11]), .CIN (b[11]),
       .COUT (n_16), .SUM (n_17));
  sky130_fd_sc_hd__fa_1 g3453(.A (a[21]), .B (c[21]), .CIN (b[21]),
       .COUT (n_14), .SUM (n_15));
  sky130_fd_sc_hd__fa_1 g3452(.A (a[10]), .B (c[10]), .CIN (b[10]),
       .COUT (n_12), .SUM (n_13));
  sky130_fd_sc_hd__fa_1 g3440(.A (a[0]), .B (c[0]), .CIN (b[0]), .COUT
       (n_10), .SUM (n_11));
  sky130_fd_sc_hd__fa_1 g3444(.A (a[28]), .B (c[28]), .CIN (b[28]),
       .COUT (n_8), .SUM (n_9));
  sky130_fd_sc_hd__fa_1 g3448(.A (a[27]), .B (c[27]), .CIN (b[27]),
       .COUT (n_6), .SUM (n_7));
  sky130_fd_sc_hd__fa_1 g3447(.A (a[13]), .B (c[13]), .CIN (b[13]),
       .COUT (n_4), .SUM (n_5));
  sky130_fd_sc_hd__fa_1 g3439(.A (a[8]), .B (c[8]), .CIN (b[8]), .COUT
       (n_2), .SUM (n_3));
  sky130_fd_sc_hd__fa_1 g3438(.A (a[24]), .B (c[24]), .CIN (b[24]),
       .COUT (n_0), .SUM (n_1));
endmodule

