
// Generated by Cadence Genus(TM) Synthesis Solution GENUS15.20 - 15.20-p004_1
// Generated on: Feb 22 2025 23:16:25

// Verification Directory fv/csa_32 

module add_unsigned_carry(A, B, CI, Z);
  input A, B, CI;
  output [1:0] Z;
  wire A, B, CI;
  wire [1:0] Z;
  wire n_6, n_7, n_8, n_9;
  xor g1 (n_9, A, B);
  nand g2 (n_6, A, B);
  nand g3 (n_7, A, CI);
  nand g4 (n_8, B, CI);
  nand g5 (Z[1], n_6, n_7, n_8);
  xor g6 (Z[0], CI, n_9);
endmodule

module increment_unsigned(A, CI, Z);
  input A, CI;
  output [1:0] Z;
  wire A, CI;
  wire [1:0] Z;
  wire n_5;
  nand g1 (n_5, A, CI);
  xor g2 (Z[0], A, CI);
  not g3 (Z[1], n_5);
endmodule

module csa_32(clk, rst_n, a, b, c, s, cout);
  input clk, rst_n;
  input [31:0] a, b, c;
  output [32:0] s;
  output cout;
  wire clk, rst_n;
  wire [31:0] a, b, c;
  wire [32:0] s;
  wire cout;
  wire [31:0] s1_reg;
  wire [31:0] c1_reg;
  wire [31:0] c2_reg;
  wire cout_reg_912, n_165, n_166, n_167, n_168, n_169, n_170, n_171;
  wire n_172, n_173, n_174, n_175, n_176, n_177, n_178, n_179;
  wire n_180, n_181, n_182, n_183, n_184, n_185, n_186, n_187;
  wire n_188, n_189, n_190, n_191, n_192, n_193, n_194, n_195;
  wire n_196, n_197, n_198, n_199, n_200, n_201, n_202, n_203;
  wire n_204, n_205, n_206, n_207, n_208, n_209, n_210, n_211;
  wire n_212, n_213, n_214, n_215, n_216, n_217, n_218, n_219;
  wire n_220, n_221, n_222, n_223, n_224, n_225, n_226, n_227;
  wire n_228, n_229, n_230, n_231, n_232, n_233, n_234, n_235;
  wire n_236, n_237, n_238, n_239, n_240, n_241, n_242, n_243;
  wire n_244, n_245, n_246, n_247, n_248, n_249, n_250, n_251;
  wire n_252, n_253, n_254, n_255, n_256, n_257, n_258, n_259;
  wire n_260, n_261, n_262, n_263, n_264, n_265, n_266, n_267;
  wire n_268, n_269, n_270, n_271, n_272, n_273, n_274, n_275;
  wire n_276, n_277, n_278, n_279, n_280, n_281, n_282, n_283;
  wire n_284, n_285, n_286, n_287, n_288, n_289, n_290, n_291;
  wire n_292, n_293, \s_reg[0]_813 , \s_reg[1]_814 , \s_reg[2]_815 ,
       \s_reg[3]_816 , \s_reg[4]_817 , \s_reg[5]_818 ;
  wire \s_reg[6]_819 , \s_reg[7]_820 , \s_reg[8]_821 , \s_reg[9]_822 ,
       \s_reg[10]_823 , \s_reg[11]_824 , \s_reg[12]_825 ,
       \s_reg[13]_826 ;
  wire \s_reg[14]_827 , \s_reg[15]_828 , \s_reg[16]_829 ,
       \s_reg[17]_830 , \s_reg[18]_831 , \s_reg[19]_832 ,
       \s_reg[20]_833 , \s_reg[21]_834 ;
  wire \s_reg[22]_835 , \s_reg[23]_836 , \s_reg[24]_837 ,
       \s_reg[25]_838 , \s_reg[26]_839 , \s_reg[27]_840 ,
       \s_reg[28]_841 , \s_reg[29]_842 ;
  wire \s_reg[30]_843 , \s_reg[31]_844 , \s_reg[32]_845 ;
  add_unsigned_carry addinc_add_21_55_I10_3(.A (a[9]), .B (b[9]), .CI
       (c[9]), .Z ({n_207, n_175}));
  add_unsigned_carry addinc_add_21_55_I11_4(.A (a[10]), .B (b[10]), .CI
       (c[10]), .Z ({n_208, n_176}));
  add_unsigned_carry addinc_add_21_55_I12_5(.A (a[11]), .B (b[11]), .CI
       (c[11]), .Z ({n_209, n_177}));
  add_unsigned_carry addinc_add_21_55_I13_6(.A (a[12]), .B (b[12]), .CI
       (c[12]), .Z ({n_210, n_178}));
  add_unsigned_carry addinc_add_21_55_I14_7(.A (a[13]), .B (b[13]), .CI
       (c[13]), .Z ({n_211, n_179}));
  add_unsigned_carry addinc_add_21_55_I15_8(.A (a[14]), .B (b[14]), .CI
       (c[14]), .Z ({n_212, n_180}));
  add_unsigned_carry addinc_add_21_55_I16_9(.A (a[15]), .B (b[15]), .CI
       (c[15]), .Z ({n_213, n_181}));
  add_unsigned_carry addinc_add_21_55_I17_10(.A (a[16]), .B (b[16]),
       .CI (c[16]), .Z ({n_214, n_182}));
  add_unsigned_carry addinc_add_21_55_I18_11(.A (a[17]), .B (b[17]),
       .CI (c[17]), .Z ({n_215, n_183}));
  add_unsigned_carry addinc_add_21_55_I19_12(.A (a[18]), .B (b[18]),
       .CI (c[18]), .Z ({n_216, n_184}));
  add_unsigned_carry addinc_add_21_55_I1_2(.A (a[0]), .B (b[0]), .CI
       (c[0]), .Z ({n_198, n_166}));
  add_unsigned_carry addinc_add_21_55_I20_14(.A (a[19]), .B (b[19]),
       .CI (c[19]), .Z ({n_217, n_185}));
  add_unsigned_carry addinc_add_21_55_I21_15(.A (a[20]), .B (b[20]),
       .CI (c[20]), .Z ({n_218, n_186}));
  add_unsigned_carry addinc_add_21_55_I22_16(.A (a[21]), .B (b[21]),
       .CI (c[21]), .Z ({n_219, n_187}));
  add_unsigned_carry addinc_add_21_55_I23_17(.A (a[22]), .B (b[22]),
       .CI (c[22]), .Z ({n_220, n_188}));
  add_unsigned_carry addinc_add_21_55_I24_18(.A (a[23]), .B (b[23]),
       .CI (c[23]), .Z ({n_221, n_189}));
  add_unsigned_carry addinc_add_21_55_I25_19(.A (a[24]), .B (b[24]),
       .CI (c[24]), .Z ({n_222, n_190}));
  add_unsigned_carry addinc_add_21_55_I26_20(.A (a[25]), .B (b[25]),
       .CI (c[25]), .Z ({n_223, n_191}));
  add_unsigned_carry addinc_add_21_55_I27_21(.A (a[26]), .B (b[26]),
       .CI (c[26]), .Z ({n_224, n_192}));
  add_unsigned_carry addinc_add_21_55_I28_22(.A (a[27]), .B (b[27]),
       .CI (c[27]), .Z ({n_225, n_193}));
  add_unsigned_carry addinc_add_21_55_I29_23(.A (a[28]), .B (b[28]),
       .CI (c[28]), .Z ({n_226, n_194}));
  add_unsigned_carry addinc_add_21_55_I2_13(.A (a[1]), .B (b[1]), .CI
       (c[1]), .Z ({n_199, n_167}));
  add_unsigned_carry addinc_add_21_55_I30_25(.A (a[29]), .B (b[29]),
       .CI (c[29]), .Z ({n_227, n_195}));
  add_unsigned_carry addinc_add_21_55_I31_26(.A (a[30]), .B (b[30]),
       .CI (c[30]), .Z ({n_228, n_196}));
  add_unsigned_carry addinc_add_21_55_I32_27(.A (a[31]), .B (b[31]),
       .CI (c[31]), .Z ({n_229, n_197}));
  add_unsigned_carry addinc_add_21_55_I3_24(.A (a[2]), .B (b[2]), .CI
       (c[2]), .Z ({n_200, n_168}));
  add_unsigned_carry addinc_add_21_55_I4_28(.A (a[3]), .B (b[3]), .CI
       (c[3]), .Z ({n_201, n_169}));
  add_unsigned_carry addinc_add_21_55_I5_29(.A (a[4]), .B (b[4]), .CI
       (c[4]), .Z ({n_202, n_170}));
  add_unsigned_carry addinc_add_21_55_I6_30(.A (a[5]), .B (b[5]), .CI
       (c[5]), .Z ({n_203, n_171}));
  add_unsigned_carry addinc_add_21_55_I7_31(.A (a[6]), .B (b[6]), .CI
       (c[6]), .Z ({n_204, n_172}));
  add_unsigned_carry addinc_add_21_55_I8_32(.A (a[7]), .B (b[7]), .CI
       (c[7]), .Z ({n_205, n_173}));
  add_unsigned_carry addinc_add_21_55_I9_63(.A (a[8]), .B (b[8]), .CI
       (c[8]), .Z ({n_206, n_174}));
  add_unsigned_carry addinc_add_36_66_I10_34(.A (s1_reg[11]), .B
       (c1_reg[10]), .CI (c2_reg[10]), .Z ({n_240, n_272}));
  add_unsigned_carry addinc_add_36_66_I11_35(.A (s1_reg[12]), .B
       (c1_reg[11]), .CI (c2_reg[11]), .Z ({n_241, n_273}));
  add_unsigned_carry addinc_add_36_66_I12_36(.A (s1_reg[13]), .B
       (c1_reg[12]), .CI (c2_reg[12]), .Z ({n_242, n_274}));
  add_unsigned_carry addinc_add_36_66_I13_37(.A (s1_reg[14]), .B
       (c1_reg[13]), .CI (c2_reg[13]), .Z ({n_243, n_275}));
  add_unsigned_carry addinc_add_36_66_I14_38(.A (s1_reg[15]), .B
       (c1_reg[14]), .CI (c2_reg[14]), .Z ({n_244, n_276}));
  add_unsigned_carry addinc_add_36_66_I15_39(.A (s1_reg[16]), .B
       (c1_reg[15]), .CI (c2_reg[15]), .Z ({n_245, n_277}));
  add_unsigned_carry addinc_add_36_66_I16_40(.A (s1_reg[17]), .B
       (c1_reg[16]), .CI (c2_reg[16]), .Z ({n_246, n_278}));
  add_unsigned_carry addinc_add_36_66_I17_41(.A (s1_reg[18]), .B
       (c1_reg[17]), .CI (c2_reg[17]), .Z ({n_247, n_279}));
  add_unsigned_carry addinc_add_36_66_I18_42(.A (s1_reg[19]), .B
       (c1_reg[18]), .CI (c2_reg[18]), .Z ({n_248, n_280}));
  add_unsigned_carry addinc_add_36_66_I19_43(.A (s1_reg[20]), .B
       (c1_reg[19]), .CI (c2_reg[19]), .Z ({n_249, n_281}));
  add_unsigned_carry addinc_add_36_66_I1_1(.A (s1_reg[2]), .B
       (c1_reg[1]), .CI (c2_reg[1]), .Z ({n_231, n_263}));
  add_unsigned_carry addinc_add_36_66_I20_45(.A (s1_reg[21]), .B
       (c1_reg[20]), .CI (c2_reg[20]), .Z ({n_250, n_282}));
  add_unsigned_carry addinc_add_36_66_I21_46(.A (s1_reg[22]), .B
       (c1_reg[21]), .CI (c2_reg[21]), .Z ({n_251, n_283}));
  add_unsigned_carry addinc_add_36_66_I22_47(.A (s1_reg[23]), .B
       (c1_reg[22]), .CI (c2_reg[22]), .Z ({n_252, n_284}));
  add_unsigned_carry addinc_add_36_66_I23_48(.A (s1_reg[24]), .B
       (c1_reg[23]), .CI (c2_reg[23]), .Z ({n_253, n_285}));
  add_unsigned_carry addinc_add_36_66_I24_49(.A (s1_reg[25]), .B
       (c1_reg[24]), .CI (c2_reg[24]), .Z ({n_254, n_286}));
  add_unsigned_carry addinc_add_36_66_I25_50(.A (s1_reg[26]), .B
       (c1_reg[25]), .CI (c2_reg[25]), .Z ({n_255, n_287}));
  add_unsigned_carry addinc_add_36_66_I26_51(.A (s1_reg[27]), .B
       (c1_reg[26]), .CI (c2_reg[26]), .Z ({n_256, n_288}));
  add_unsigned_carry addinc_add_36_66_I27_52(.A (s1_reg[28]), .B
       (c1_reg[27]), .CI (c2_reg[27]), .Z ({n_257, n_289}));
  add_unsigned_carry addinc_add_36_66_I28_53(.A (s1_reg[29]), .B
       (c1_reg[28]), .CI (c2_reg[28]), .Z ({n_258, n_290}));
  add_unsigned_carry addinc_add_36_66_I29_54(.A (s1_reg[30]), .B
       (c1_reg[29]), .CI (c2_reg[29]), .Z ({n_259, n_291}));
  add_unsigned_carry addinc_add_36_66_I2_44(.A (s1_reg[3]), .B
       (c1_reg[2]), .CI (c2_reg[2]), .Z ({n_232, n_264}));
  add_unsigned_carry addinc_add_36_66_I30_56(.A (s1_reg[31]), .B
       (c1_reg[30]), .CI (c2_reg[30]), .Z ({n_260, n_292}));
  add_unsigned_carry addinc_add_36_66_I3_55(.A (s1_reg[4]), .B
       (c1_reg[3]), .CI (c2_reg[3]), .Z ({n_233, n_265}));
  add_unsigned_carry addinc_add_36_66_I4_57(.A (s1_reg[5]), .B
       (c1_reg[4]), .CI (c2_reg[4]), .Z ({n_234, n_266}));
  add_unsigned_carry addinc_add_36_66_I5_58(.A (s1_reg[6]), .B
       (c1_reg[5]), .CI (c2_reg[5]), .Z ({n_235, n_267}));
  add_unsigned_carry addinc_add_36_66_I6_59(.A (s1_reg[7]), .B
       (c1_reg[6]), .CI (c2_reg[6]), .Z ({n_236, n_268}));
  add_unsigned_carry addinc_add_36_66_I7_60(.A (s1_reg[8]), .B
       (c1_reg[7]), .CI (c2_reg[7]), .Z ({n_237, n_269}));
  add_unsigned_carry addinc_add_36_66_I8_61(.A (s1_reg[9]), .B
       (c1_reg[8]), .CI (c2_reg[8]), .Z ({n_238, n_270}));
  add_unsigned_carry addinc_add_36_66_I9_62(.A (s1_reg[10]), .B
       (c1_reg[9]), .CI (c2_reg[9]), .Z ({n_239, n_271}));
  add_unsigned_carry addinc_add_38_62_64(.A (s1_reg[31]), .B
       (c1_reg[31]), .CI (c2_reg[31]), .Z ({n_261, n_293}));
  increment_unsigned inc_add_34_48_33(.A (c1_reg[0]), .CI (s1_reg[1]),
       .Z ({n_230, n_262}));
  CDN_flop \c1_reg_reg[0] (.clk (clk), .d (n_198), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (c1_reg[0]));
  CDN_flop \c1_reg_reg[10] (.clk (clk), .d (n_208), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (c1_reg[10]));
  CDN_flop \c1_reg_reg[11] (.clk (clk), .d (n_209), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (c1_reg[11]));
  CDN_flop \c1_reg_reg[12] (.clk (clk), .d (n_210), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (c1_reg[12]));
  CDN_flop \c1_reg_reg[13] (.clk (clk), .d (n_211), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (c1_reg[13]));
  CDN_flop \c1_reg_reg[14] (.clk (clk), .d (n_212), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (c1_reg[14]));
  CDN_flop \c1_reg_reg[15] (.clk (clk), .d (n_213), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (c1_reg[15]));
  CDN_flop \c1_reg_reg[16] (.clk (clk), .d (n_214), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (c1_reg[16]));
  CDN_flop \c1_reg_reg[17] (.clk (clk), .d (n_215), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (c1_reg[17]));
  CDN_flop \c1_reg_reg[18] (.clk (clk), .d (n_216), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (c1_reg[18]));
  CDN_flop \c1_reg_reg[19] (.clk (clk), .d (n_217), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (c1_reg[19]));
  CDN_flop \c1_reg_reg[1] (.clk (clk), .d (n_199), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (c1_reg[1]));
  CDN_flop \c1_reg_reg[20] (.clk (clk), .d (n_218), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (c1_reg[20]));
  CDN_flop \c1_reg_reg[21] (.clk (clk), .d (n_219), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (c1_reg[21]));
  CDN_flop \c1_reg_reg[22] (.clk (clk), .d (n_220), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (c1_reg[22]));
  CDN_flop \c1_reg_reg[23] (.clk (clk), .d (n_221), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (c1_reg[23]));
  CDN_flop \c1_reg_reg[24] (.clk (clk), .d (n_222), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (c1_reg[24]));
  CDN_flop \c1_reg_reg[25] (.clk (clk), .d (n_223), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (c1_reg[25]));
  CDN_flop \c1_reg_reg[26] (.clk (clk), .d (n_224), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (c1_reg[26]));
  CDN_flop \c1_reg_reg[27] (.clk (clk), .d (n_225), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (c1_reg[27]));
  CDN_flop \c1_reg_reg[28] (.clk (clk), .d (n_226), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (c1_reg[28]));
  CDN_flop \c1_reg_reg[29] (.clk (clk), .d (n_227), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (c1_reg[29]));
  CDN_flop \c1_reg_reg[2] (.clk (clk), .d (n_200), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (c1_reg[2]));
  CDN_flop \c1_reg_reg[30] (.clk (clk), .d (n_228), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (c1_reg[30]));
  CDN_flop \c1_reg_reg[31] (.clk (clk), .d (n_229), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (c1_reg[31]));
  CDN_flop \c1_reg_reg[3] (.clk (clk), .d (n_201), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (c1_reg[3]));
  CDN_flop \c1_reg_reg[4] (.clk (clk), .d (n_202), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (c1_reg[4]));
  CDN_flop \c1_reg_reg[5] (.clk (clk), .d (n_203), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (c1_reg[5]));
  CDN_flop \c1_reg_reg[6] (.clk (clk), .d (n_204), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (c1_reg[6]));
  CDN_flop \c1_reg_reg[7] (.clk (clk), .d (n_205), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (c1_reg[7]));
  CDN_flop \c1_reg_reg[8] (.clk (clk), .d (n_206), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (c1_reg[8]));
  CDN_flop \c1_reg_reg[9] (.clk (clk), .d (n_207), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (c1_reg[9]));
  CDN_flop \c2_reg_reg[10] (.clk (clk), .d (n_239), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (c2_reg[10]));
  CDN_flop \c2_reg_reg[11] (.clk (clk), .d (n_240), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (c2_reg[11]));
  CDN_flop \c2_reg_reg[12] (.clk (clk), .d (n_241), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (c2_reg[12]));
  CDN_flop \c2_reg_reg[13] (.clk (clk), .d (n_242), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (c2_reg[13]));
  CDN_flop \c2_reg_reg[14] (.clk (clk), .d (n_243), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (c2_reg[14]));
  CDN_flop \c2_reg_reg[15] (.clk (clk), .d (n_244), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (c2_reg[15]));
  CDN_flop \c2_reg_reg[16] (.clk (clk), .d (n_245), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (c2_reg[16]));
  CDN_flop \c2_reg_reg[17] (.clk (clk), .d (n_246), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (c2_reg[17]));
  CDN_flop \c2_reg_reg[18] (.clk (clk), .d (n_247), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (c2_reg[18]));
  CDN_flop \c2_reg_reg[19] (.clk (clk), .d (n_248), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (c2_reg[19]));
  CDN_flop \c2_reg_reg[1] (.clk (clk), .d (n_230), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (c2_reg[1]));
  CDN_flop \c2_reg_reg[20] (.clk (clk), .d (n_249), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (c2_reg[20]));
  CDN_flop \c2_reg_reg[21] (.clk (clk), .d (n_250), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (c2_reg[21]));
  CDN_flop \c2_reg_reg[22] (.clk (clk), .d (n_251), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (c2_reg[22]));
  CDN_flop \c2_reg_reg[23] (.clk (clk), .d (n_252), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (c2_reg[23]));
  CDN_flop \c2_reg_reg[24] (.clk (clk), .d (n_253), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (c2_reg[24]));
  CDN_flop \c2_reg_reg[25] (.clk (clk), .d (n_254), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (c2_reg[25]));
  CDN_flop \c2_reg_reg[26] (.clk (clk), .d (n_255), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (c2_reg[26]));
  CDN_flop \c2_reg_reg[27] (.clk (clk), .d (n_256), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (c2_reg[27]));
  CDN_flop \c2_reg_reg[28] (.clk (clk), .d (n_257), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (c2_reg[28]));
  CDN_flop \c2_reg_reg[29] (.clk (clk), .d (n_258), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (c2_reg[29]));
  CDN_flop \c2_reg_reg[2] (.clk (clk), .d (n_231), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (c2_reg[2]));
  CDN_flop \c2_reg_reg[30] (.clk (clk), .d (n_259), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (c2_reg[30]));
  CDN_flop \c2_reg_reg[31] (.clk (clk), .d (n_260), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (c2_reg[31]));
  CDN_flop \c2_reg_reg[3] (.clk (clk), .d (n_232), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (c2_reg[3]));
  CDN_flop \c2_reg_reg[4] (.clk (clk), .d (n_233), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (c2_reg[4]));
  CDN_flop \c2_reg_reg[5] (.clk (clk), .d (n_234), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (c2_reg[5]));
  CDN_flop \c2_reg_reg[6] (.clk (clk), .d (n_235), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (c2_reg[6]));
  CDN_flop \c2_reg_reg[7] (.clk (clk), .d (n_236), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (c2_reg[7]));
  CDN_flop \c2_reg_reg[8] (.clk (clk), .d (n_237), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (c2_reg[8]));
  CDN_flop \c2_reg_reg[9] (.clk (clk), .d (n_238), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (c2_reg[9]));
  CDN_flop cout_reg(.clk (clk), .d (cout_reg_912), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (cout));
  CDN_flop cout_reg_reg(.clk (clk), .d (n_261), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (cout_reg_912));
  not g1 (n_165, rst_n);
  CDN_flop \s1_reg_reg[0] (.clk (clk), .d (n_166), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (s1_reg[0]));
  CDN_flop \s1_reg_reg[10] (.clk (clk), .d (n_176), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (s1_reg[10]));
  CDN_flop \s1_reg_reg[11] (.clk (clk), .d (n_177), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (s1_reg[11]));
  CDN_flop \s1_reg_reg[12] (.clk (clk), .d (n_178), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (s1_reg[12]));
  CDN_flop \s1_reg_reg[13] (.clk (clk), .d (n_179), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (s1_reg[13]));
  CDN_flop \s1_reg_reg[14] (.clk (clk), .d (n_180), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (s1_reg[14]));
  CDN_flop \s1_reg_reg[15] (.clk (clk), .d (n_181), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (s1_reg[15]));
  CDN_flop \s1_reg_reg[16] (.clk (clk), .d (n_182), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (s1_reg[16]));
  CDN_flop \s1_reg_reg[17] (.clk (clk), .d (n_183), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (s1_reg[17]));
  CDN_flop \s1_reg_reg[18] (.clk (clk), .d (n_184), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (s1_reg[18]));
  CDN_flop \s1_reg_reg[19] (.clk (clk), .d (n_185), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (s1_reg[19]));
  CDN_flop \s1_reg_reg[1] (.clk (clk), .d (n_167), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (s1_reg[1]));
  CDN_flop \s1_reg_reg[20] (.clk (clk), .d (n_186), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (s1_reg[20]));
  CDN_flop \s1_reg_reg[21] (.clk (clk), .d (n_187), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (s1_reg[21]));
  CDN_flop \s1_reg_reg[22] (.clk (clk), .d (n_188), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (s1_reg[22]));
  CDN_flop \s1_reg_reg[23] (.clk (clk), .d (n_189), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (s1_reg[23]));
  CDN_flop \s1_reg_reg[24] (.clk (clk), .d (n_190), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (s1_reg[24]));
  CDN_flop \s1_reg_reg[25] (.clk (clk), .d (n_191), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (s1_reg[25]));
  CDN_flop \s1_reg_reg[26] (.clk (clk), .d (n_192), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (s1_reg[26]));
  CDN_flop \s1_reg_reg[27] (.clk (clk), .d (n_193), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (s1_reg[27]));
  CDN_flop \s1_reg_reg[28] (.clk (clk), .d (n_194), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (s1_reg[28]));
  CDN_flop \s1_reg_reg[29] (.clk (clk), .d (n_195), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (s1_reg[29]));
  CDN_flop \s1_reg_reg[2] (.clk (clk), .d (n_168), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (s1_reg[2]));
  CDN_flop \s1_reg_reg[30] (.clk (clk), .d (n_196), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (s1_reg[30]));
  CDN_flop \s1_reg_reg[31] (.clk (clk), .d (n_197), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (s1_reg[31]));
  CDN_flop \s1_reg_reg[3] (.clk (clk), .d (n_169), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (s1_reg[3]));
  CDN_flop \s1_reg_reg[4] (.clk (clk), .d (n_170), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (s1_reg[4]));
  CDN_flop \s1_reg_reg[5] (.clk (clk), .d (n_171), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (s1_reg[5]));
  CDN_flop \s1_reg_reg[6] (.clk (clk), .d (n_172), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (s1_reg[6]));
  CDN_flop \s1_reg_reg[7] (.clk (clk), .d (n_173), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (s1_reg[7]));
  CDN_flop \s1_reg_reg[8] (.clk (clk), .d (n_174), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (s1_reg[8]));
  CDN_flop \s1_reg_reg[9] (.clk (clk), .d (n_175), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (s1_reg[9]));
  CDN_flop \s_reg[0] (.clk (clk), .d (\s_reg[0]_813 ), .sena (1'b1),
       .aclr (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (s[0]));
  CDN_flop \s_reg[10] (.clk (clk), .d (\s_reg[10]_823 ), .sena (1'b1),
       .aclr (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (s[10]));
  CDN_flop \s_reg[11] (.clk (clk), .d (\s_reg[11]_824 ), .sena (1'b1),
       .aclr (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (s[11]));
  CDN_flop \s_reg[12] (.clk (clk), .d (\s_reg[12]_825 ), .sena (1'b1),
       .aclr (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (s[12]));
  CDN_flop \s_reg[13] (.clk (clk), .d (\s_reg[13]_826 ), .sena (1'b1),
       .aclr (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (s[13]));
  CDN_flop \s_reg[14] (.clk (clk), .d (\s_reg[14]_827 ), .sena (1'b1),
       .aclr (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (s[14]));
  CDN_flop \s_reg[15] (.clk (clk), .d (\s_reg[15]_828 ), .sena (1'b1),
       .aclr (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (s[15]));
  CDN_flop \s_reg[16] (.clk (clk), .d (\s_reg[16]_829 ), .sena (1'b1),
       .aclr (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (s[16]));
  CDN_flop \s_reg[17] (.clk (clk), .d (\s_reg[17]_830 ), .sena (1'b1),
       .aclr (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (s[17]));
  CDN_flop \s_reg[18] (.clk (clk), .d (\s_reg[18]_831 ), .sena (1'b1),
       .aclr (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (s[18]));
  CDN_flop \s_reg[19] (.clk (clk), .d (\s_reg[19]_832 ), .sena (1'b1),
       .aclr (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (s[19]));
  CDN_flop \s_reg[1] (.clk (clk), .d (\s_reg[1]_814 ), .sena (1'b1),
       .aclr (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (s[1]));
  CDN_flop \s_reg[20] (.clk (clk), .d (\s_reg[20]_833 ), .sena (1'b1),
       .aclr (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (s[20]));
  CDN_flop \s_reg[21] (.clk (clk), .d (\s_reg[21]_834 ), .sena (1'b1),
       .aclr (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (s[21]));
  CDN_flop \s_reg[22] (.clk (clk), .d (\s_reg[22]_835 ), .sena (1'b1),
       .aclr (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (s[22]));
  CDN_flop \s_reg[23] (.clk (clk), .d (\s_reg[23]_836 ), .sena (1'b1),
       .aclr (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (s[23]));
  CDN_flop \s_reg[24] (.clk (clk), .d (\s_reg[24]_837 ), .sena (1'b1),
       .aclr (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (s[24]));
  CDN_flop \s_reg[25] (.clk (clk), .d (\s_reg[25]_838 ), .sena (1'b1),
       .aclr (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (s[25]));
  CDN_flop \s_reg[26] (.clk (clk), .d (\s_reg[26]_839 ), .sena (1'b1),
       .aclr (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (s[26]));
  CDN_flop \s_reg[27] (.clk (clk), .d (\s_reg[27]_840 ), .sena (1'b1),
       .aclr (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (s[27]));
  CDN_flop \s_reg[28] (.clk (clk), .d (\s_reg[28]_841 ), .sena (1'b1),
       .aclr (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (s[28]));
  CDN_flop \s_reg[29] (.clk (clk), .d (\s_reg[29]_842 ), .sena (1'b1),
       .aclr (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (s[29]));
  CDN_flop \s_reg[2] (.clk (clk), .d (\s_reg[2]_815 ), .sena (1'b1),
       .aclr (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (s[2]));
  CDN_flop \s_reg[30] (.clk (clk), .d (\s_reg[30]_843 ), .sena (1'b1),
       .aclr (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (s[30]));
  CDN_flop \s_reg[31] (.clk (clk), .d (\s_reg[31]_844 ), .sena (1'b1),
       .aclr (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (s[31]));
  CDN_flop \s_reg[32] (.clk (clk), .d (\s_reg[32]_845 ), .sena (1'b1),
       .aclr (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (s[32]));
  CDN_flop \s_reg[3] (.clk (clk), .d (\s_reg[3]_816 ), .sena (1'b1),
       .aclr (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (s[3]));
  CDN_flop \s_reg[4] (.clk (clk), .d (\s_reg[4]_817 ), .sena (1'b1),
       .aclr (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (s[4]));
  CDN_flop \s_reg[5] (.clk (clk), .d (\s_reg[5]_818 ), .sena (1'b1),
       .aclr (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (s[5]));
  CDN_flop \s_reg[6] (.clk (clk), .d (\s_reg[6]_819 ), .sena (1'b1),
       .aclr (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (s[6]));
  CDN_flop \s_reg[7] (.clk (clk), .d (\s_reg[7]_820 ), .sena (1'b1),
       .aclr (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (s[7]));
  CDN_flop \s_reg[8] (.clk (clk), .d (\s_reg[8]_821 ), .sena (1'b1),
       .aclr (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (s[8]));
  CDN_flop \s_reg[9] (.clk (clk), .d (\s_reg[9]_822 ), .sena (1'b1),
       .aclr (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (s[9]));
  CDN_flop \s_reg_reg[0] (.clk (clk), .d (s1_reg[0]), .sena (1'b1),
       .aclr (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\s_reg[0]_813 ));
  CDN_flop \s_reg_reg[10] (.clk (clk), .d (n_271), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\s_reg[10]_823 ));
  CDN_flop \s_reg_reg[11] (.clk (clk), .d (n_272), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\s_reg[11]_824 ));
  CDN_flop \s_reg_reg[12] (.clk (clk), .d (n_273), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\s_reg[12]_825 ));
  CDN_flop \s_reg_reg[13] (.clk (clk), .d (n_274), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\s_reg[13]_826 ));
  CDN_flop \s_reg_reg[14] (.clk (clk), .d (n_275), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\s_reg[14]_827 ));
  CDN_flop \s_reg_reg[15] (.clk (clk), .d (n_276), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\s_reg[15]_828 ));
  CDN_flop \s_reg_reg[16] (.clk (clk), .d (n_277), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\s_reg[16]_829 ));
  CDN_flop \s_reg_reg[17] (.clk (clk), .d (n_278), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\s_reg[17]_830 ));
  CDN_flop \s_reg_reg[18] (.clk (clk), .d (n_279), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\s_reg[18]_831 ));
  CDN_flop \s_reg_reg[19] (.clk (clk), .d (n_280), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\s_reg[19]_832 ));
  CDN_flop \s_reg_reg[1] (.clk (clk), .d (n_262), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\s_reg[1]_814 ));
  CDN_flop \s_reg_reg[20] (.clk (clk), .d (n_281), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\s_reg[20]_833 ));
  CDN_flop \s_reg_reg[21] (.clk (clk), .d (n_282), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\s_reg[21]_834 ));
  CDN_flop \s_reg_reg[22] (.clk (clk), .d (n_283), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\s_reg[22]_835 ));
  CDN_flop \s_reg_reg[23] (.clk (clk), .d (n_284), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\s_reg[23]_836 ));
  CDN_flop \s_reg_reg[24] (.clk (clk), .d (n_285), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\s_reg[24]_837 ));
  CDN_flop \s_reg_reg[25] (.clk (clk), .d (n_286), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\s_reg[25]_838 ));
  CDN_flop \s_reg_reg[26] (.clk (clk), .d (n_287), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\s_reg[26]_839 ));
  CDN_flop \s_reg_reg[27] (.clk (clk), .d (n_288), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\s_reg[27]_840 ));
  CDN_flop \s_reg_reg[28] (.clk (clk), .d (n_289), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\s_reg[28]_841 ));
  CDN_flop \s_reg_reg[29] (.clk (clk), .d (n_290), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\s_reg[29]_842 ));
  CDN_flop \s_reg_reg[2] (.clk (clk), .d (n_263), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\s_reg[2]_815 ));
  CDN_flop \s_reg_reg[30] (.clk (clk), .d (n_291), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\s_reg[30]_843 ));
  CDN_flop \s_reg_reg[31] (.clk (clk), .d (n_292), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\s_reg[31]_844 ));
  CDN_flop \s_reg_reg[32] (.clk (clk), .d (n_293), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\s_reg[32]_845 ));
  CDN_flop \s_reg_reg[3] (.clk (clk), .d (n_264), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\s_reg[3]_816 ));
  CDN_flop \s_reg_reg[4] (.clk (clk), .d (n_265), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\s_reg[4]_817 ));
  CDN_flop \s_reg_reg[5] (.clk (clk), .d (n_266), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\s_reg[5]_818 ));
  CDN_flop \s_reg_reg[6] (.clk (clk), .d (n_267), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\s_reg[6]_819 ));
  CDN_flop \s_reg_reg[7] (.clk (clk), .d (n_268), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\s_reg[7]_820 ));
  CDN_flop \s_reg_reg[8] (.clk (clk), .d (n_269), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\s_reg[8]_821 ));
  CDN_flop \s_reg_reg[9] (.clk (clk), .d (n_270), .sena (1'b1), .aclr
       (n_165), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (\s_reg[9]_822 ));
endmodule

`ifdef RC_CDN_GENERIC_GATE
`else
module CDN_flop(clk, d, sena, aclr, apre, srl, srd, q);
  input clk, d, sena, aclr, apre, srl, srd;
  output q;
  wire clk, d, sena, aclr, apre, srl, srd;
  wire q;
  reg  qi;
  assign #1 q = qi;
  always 
    @(posedge clk or posedge apre or posedge aclr) 
      if (aclr) 
        qi <= 0;
      else if (apre) 
          qi <= 1;
        else if (srl) 
            qi <= srd;
          else begin
            if (sena) 
              qi <= d;
          end
  initial 
    qi <= 1'b0;
endmodule
`endif
