def mod_mult(a, b, prime):
    return (a * b) % prime

# Danh sách test case với số dạng hex
testcases = [
    (0x7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBB, 
     0x7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5B),
    (0x7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5B, 
     0x7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEF91),
    (0x7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF82ED, 
     0x7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFB2B),
    (0x7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEF91, 
     0x7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE1C75)
]

prime = 0x7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFED  # Số nguyên tố lớn
alu_sel = 0b011  # Chọn phép nhân

print("KQ modulo  hex:")
for i, (a, b) in enumerate(testcases, start=1):
    result = mod_mult(a, b, prime)
    print(f"Testcase {i}:")
    print(f"alu_sel = {alu_sel:03b}")
    print(f"a       = {a:064X}")
    print(f"b       = {b:064X}")
    print(f"prime   = {prime:064X}")
    print(f"Result  = {result:064X}\n")
